### ISSUE TITLE
Theme not selectable in Atrium

### ISSUE THREAD

**Issue by rovo79** [developmentseed/singular#1]
Hello,
 I've added this theme to my sites/all/themes directory along with the Tao base theme. When I go to the admin/build/themes page of my drupal install, they will not show up there in the list? Any ideas on what I am missing would be great.

Thank You

**Comment by rovo79** [comment]
This solved:

"you can have themes show up in the admin/build/themes page in Atrium by adding 'atrium = "1.x"' to the theme's .info file "  - provided by yhahn

**Comment by yhahn** [comment]
Closing.
